apiVersion: v1
kind: Service
metadata:
  name: {{ include "asibot.fullname" . }}
  labels:
    {{- include "asibot.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "asibot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: dashboard
      port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
