"""Load test suite for the Asibot MCP server.

Simulates 1000+ concurrent users hitting the MCP server over streamable-http
transport. Tests authentication, tool calls, setup flows, rate limiting, and
session reuse.

Usage (headless with pre-seeded users):
    locust -f tests/load/locustfile.py --host http://localhost:8080 \
        --headless --users 1000 --spawn-rate 5 --run-time 10m \
        --csv results/asibot_load

Pre-seed users first:
    python tests/load/seed_test_users.py --output tests/load/test_users.csv

Ramp-up from 10 to 1000 users over 5 minutes is configured via the
StepLoadShape class (step load shape).
"""

from __future__ import annotations

import csv
import json
import logging
import os
import random
import string
import sys
import time
import uuid
from typing import Any

from locust import HttpUser, LoadTestShape, between, events, tag, task
from locust.runners import MasterRunner, WorkerRunner

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Pre-seeded API key pool (loaded from CSV generated by seed_test_users.py)
# ---------------------------------------------------------------------------

_CSV_PATH = os.environ.get(
    "LOCUST_USERS_CSV",
    os.path.join(os.path.dirname(__file__), "test_users.csv"),
)

_seeded_keys: list[dict[str, str]] | None = None


def _load_seeded_keys() -> list[dict[str, str]]:
    """Load pre-seeded user_id,api_key pairs from CSV.

    Falls back to generating fake keys if the CSV does not exist (legacy mode),
    but prints a loud warning since those requests will get auth errors.
    """
    global _seeded_keys
    if _seeded_keys is not None:
        return _seeded_keys

    if os.path.exists(_CSV_PATH):
        with open(_CSV_PATH, newline="") as f:
            reader = csv.DictReader(f)
            _seeded_keys = [row for row in reader if row.get("api_key")]
        logger.info("Loaded %d pre-seeded API keys from %s", len(_seeded_keys), _CSV_PATH)
    else:
        logger.warning(
            "No pre-seeded users CSV found at %s. "
            "Generating fake API keys -- most requests will fail auth. "
            "Run seed_test_users.py first for realistic testing.",
            _CSV_PATH,
        )
        _seeded_keys = [
            {"user_id": f"fake-{i}@test.example.com", "api_key": f"asb_{''.join(random.choices(string.ascii_letters + string.digits, k=43))}"}
            for i in range(200)
        ]

    return _seeded_keys


# ---------------------------------------------------------------------------
# Custom metrics (tracked as Locust stats entries via request_success/failure)
# ---------------------------------------------------------------------------

_custom_metrics: dict[str, list[float]] = {
    "auth_latency": [],
    "tool_call_latency": [],
    "rate_limit_hits": [],
}


@events.request.add_listener
def _on_request(request_type, name, response_time, response_length, exception, **kwargs):
    """Classify every request into custom metric buckets."""
    if exception is None:
        if "auth" in name.lower() or "initialize" in name.lower():
            _custom_metrics["auth_latency"].append(response_time)
        elif "tool_call" in name.lower():
            _custom_metrics["tool_call_latency"].append(response_time)
    # Track rate-limit responses (HTTP 429 or MCP-level rate limit errors)
    response = kwargs.get("response")
    if response is not None and response.status_code == 429:
        _custom_metrics["rate_limit_hits"].append(response_time)


def _percentile(values: list[float], pct: float) -> float:
    """Calculate the given percentile from a sorted list of values."""
    if not values:
        return 0.0
    idx = int(len(values) * pct)
    idx = min(idx, len(values) - 1)
    return values[idx]


@events.test_stop.add_listener
def _on_test_stop(environment, **kwargs):
    """Print a summary of custom metrics and benchmark pass/fail when the test ends."""
    print("\n" + "=" * 70)
    print("CUSTOM METRICS SUMMARY")
    print("=" * 70)
    for metric_name, values in _custom_metrics.items():
        if not values:
            print(f"  {metric_name}: no data")
            continue
        count = len(values)
        avg = sum(values) / count
        sorted_vals = sorted(values)
        p50 = _percentile(sorted_vals, 0.50)
        p95 = _percentile(sorted_vals, 0.95)
        p99 = _percentile(sorted_vals, 0.99)
        print(
            f"  {metric_name}: count={count}  avg={avg:.1f}ms  "
            f"p50={p50:.1f}ms  p95={p95:.1f}ms  p99={p99:.1f}ms"
        )
    print("=" * 70)

    # --- Benchmark validation ---
    print("\n" + "=" * 70)
    print("BENCHMARK VALIDATION")
    print("=" * 70)

    checks: list[tuple[str, bool, str]] = []

    # Throughput: aggregate RPS from Locust stats
    stats = environment.runner.stats if environment.runner else None
    total_rps = 0.0
    total_reqs = 0
    total_fails = 0
    if stats:
        total = stats.total
        total_rps = total.current_rps if hasattr(total, "current_rps") else 0
        total_reqs = total.num_requests
        total_fails = total.num_failures

    checks.append((
        "Throughput >= 500 req/s",
        total_rps >= 500,
        f"{total_rps:.1f} req/s",
    ))

    # Auth latency p95 < 100ms
    auth_vals = sorted(_custom_metrics.get("auth_latency", []))
    auth_p95 = _percentile(auth_vals, 0.95) if auth_vals else 0
    checks.append((
        "Auth latency p95 < 100ms",
        auth_p95 < 100 if auth_vals else False,
        f"{auth_p95:.1f}ms" if auth_vals else "no data",
    ))

    # Tool call latency p95 < 200ms
    tool_vals = sorted(_custom_metrics.get("tool_call_latency", []))
    tool_p95 = _percentile(tool_vals, 0.95) if tool_vals else 0
    checks.append((
        "Tool call latency p95 < 200ms",
        tool_p95 < 200 if tool_vals else False,
        f"{tool_p95:.1f}ms" if tool_vals else "no data",
    ))

    # Error rate < 1%
    error_rate = (total_fails / total_reqs * 100) if total_reqs > 0 else 100
    checks.append((
        "Error rate < 1%",
        error_rate < 1,
        f"{error_rate:.2f}%",
    ))

    all_passed = True
    for label, passed, value in checks:
        status = "PASS" if passed else "FAIL"
        if not passed:
            all_passed = False
        print(f"  [{status}] {label}: {value}")

    print("=" * 70)
    if all_passed:
        print("RESULT: ALL BENCHMARKS PASSED")
    else:
        print("RESULT: SOME BENCHMARKS FAILED")
    print("=" * 70 + "\n")


# ---------------------------------------------------------------------------
# MCP Protocol helpers
# ---------------------------------------------------------------------------

MCP_PATH = "/mcp"
JSONRPC_VERSION = "2.0"


def _jsonrpc_request(method: str, params: dict | None = None, req_id: int | None = None) -> dict:
    """Build a JSON-RPC 2.0 request envelope."""
    msg: dict[str, Any] = {
        "jsonrpc": JSONRPC_VERSION,
        "method": method,
    }
    if params is not None:
        msg["params"] = params
    if req_id is not None:
        msg["id"] = req_id
    else:
        msg["id"] = random.randint(1, 2**31)
    return msg


def _make_tool_call(tool_name: str, arguments: dict | None = None, req_id: int | None = None) -> dict:
    """Build a JSON-RPC tools/call request."""
    return _jsonrpc_request(
        "tools/call",
        params={"name": tool_name, "arguments": arguments or {}},
        req_id=req_id,
    )


def _make_initialize_request(req_id: int | None = None) -> dict:
    """Build an MCP initialize request."""
    return _jsonrpc_request(
        "initialize",
        params={
            "protocolVersion": "2025-03-26",
            "capabilities": {},
            "clientInfo": {
                "name": "locust-load-test",
                "version": "1.0.0",
            },
        },
        req_id=req_id,
    )


def _make_list_tools_request(req_id: int | None = None) -> dict:
    """Build an MCP tools/list request."""
    return _jsonrpc_request("tools/list", req_id=req_id)


# ---------------------------------------------------------------------------
# Realistic search queries and repo names for tool calls
# ---------------------------------------------------------------------------

SEARCH_QUERIES = [
    "authentication middleware",
    "database migration",
    "rate limiter implementation",
    "CI/CD pipeline",
    "kubernetes deployment",
    "REST API handler",
    "OAuth2 flow",
    "websocket connection",
    "caching strategy",
    "error handling patterns",
    "unit test fixtures",
    "logging configuration",
    "feature flag service",
    "message queue consumer",
    "gRPC service definition",
]

REPO_NAMES = [
    "api-gateway",
    "auth-service",
    "web-frontend",
    "data-pipeline",
    "ml-platform",
    "infra-terraform",
    "mobile-app",
    "docs-site",
    "shared-libs",
    "analytics-dashboard",
]

JIRA_PROJECTS = ["ENG", "PLAT", "SEC", "DATA", "OPS"]

CONFLUENCE_QUERIES = [
    "onboarding guide",
    "architecture decision record",
    "runbook production",
    "API design guidelines",
    "security policy",
]


# ---------------------------------------------------------------------------
# Locust User class
# ---------------------------------------------------------------------------


class McpUser(HttpUser):
    """Simulates a single user interacting with the Asibot MCP server.

    Each user:
    1. Picks a pre-seeded API key from the CSV pool
    2. Initializes an MCP session (authenticate + get session ID)
    3. Lists available tools
    4. Makes tool calls with realistic parameters
    5. Occasionally triggers rate limiting by bursting requests
    6. Reuses the session ID for subsequent requests (session caching)
    """

    # Think time between requests: 1-5 seconds simulates real user pauses
    wait_time = between(1.0, 5.0)

    # Track per-user state
    api_key: str = ""
    user_id: str = ""
    session_id: str | None = None
    _initialized: bool = False
    _request_counter: int = 0

    def on_start(self):
        """Called when a simulated user starts. Pick a pre-seeded API key and initialize."""
        keys = _load_seeded_keys()
        entry = random.choice(keys)
        self.api_key = entry["api_key"]
        self.user_id = entry["user_id"]
        self.session_id = None
        self._initialized = False
        self._request_counter = 0
        self._initialize_session()

    def _auth_headers(self) -> dict[str, str]:
        """Return headers with Bearer auth and optional session ID."""
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        }
        if self.session_id:
            headers["Mcp-Session-Id"] = self.session_id
        return headers

    def _send_mcp_request(self, payload: dict, name: str) -> Any:
        """Send a JSON-RPC request to the MCP endpoint.

        Handles session ID extraction from response headers and tracks
        success/failure for Locust metrics.
        """
        self._request_counter += 1
        headers = self._auth_headers()

        with self.client.post(
            MCP_PATH,
            json=payload,
            headers=headers,
            name=name,
            catch_response=True,
        ) as response:
            # Extract session ID from response headers if present
            new_session_id = response.headers.get("Mcp-Session-Id")
            if new_session_id:
                self.session_id = new_session_id

            if response.status_code == 429:
                # Rate limited -- expected under load, mark as success for
                # tracking but record in custom metrics
                _custom_metrics["rate_limit_hits"].append(response.elapsed.total_seconds() * 1000)
                response.success()
                return {"rate_limited": True}

            if response.status_code >= 400:
                response.failure(f"HTTP {response.status_code}: {response.text[:200]}")
                return None

            # Parse the response -- MCP over streamable-http may return
            # SSE events or plain JSON depending on the server mode
            try:
                content_type = response.headers.get("Content-Type", "")
                if "text/event-stream" in content_type:
                    # Parse SSE: extract the last JSON data line
                    body = response.text
                    result = _parse_sse_response(body)
                    if result is not None:
                        response.success()
                        return result
                    # If no parseable result, still mark success (could be
                    # a notification-only stream)
                    response.success()
                    return {"sse": True, "raw": body[:500]}
                else:
                    result = response.json()
                    if "error" in result:
                        # JSON-RPC error -- still a valid protocol response
                        error_msg = result["error"].get("message", "unknown")
                        response.success()
                        return result
                    response.success()
                    return result
            except Exception as e:
                response.failure(f"Parse error: {e}")
                return None

    def _initialize_session(self):
        """Perform the MCP initialize handshake."""
        payload = _make_initialize_request()
        result = self._send_mcp_request(payload, "MCP initialize (auth)")
        if result and not isinstance(result, dict):
            return

        self._initialized = True

        # Send initialized notification (no response expected, but we
        # track the request for latency metrics)
        notification = {
            "jsonrpc": JSONRPC_VERSION,
            "method": "notifications/initialized",
        }
        self._send_mcp_request(notification, "MCP initialized notification")

    # --- Task definitions (weighted by realistic usage patterns) ---

    @task(20)
    @tag("tools", "list")
    def list_tools(self):
        """List available MCP tools. High frequency -- clients call this on
        every reconnect and periodically to refresh the tool list."""
        payload = _make_list_tools_request()
        self._send_mcp_request(payload, "tool_call: tools/list")

    @task(15)
    @tag("tools", "health")
    def health_check(self):
        """Call asibot_health (no auth required). Simulates monitoring probes."""
        payload = _make_tool_call("asibot_health")
        self._send_mcp_request(payload, "tool_call: asibot_health")

    @task(10)
    @tag("tools", "whoami")
    def whoami(self):
        """Check user identity via asibot_whoami."""
        payload = _make_tool_call("asibot_whoami")
        self._send_mcp_request(payload, "tool_call: asibot_whoami")

    @task(10)
    @tag("tools", "services")
    def list_services(self):
        """List connected services via asibot_services."""
        payload = _make_tool_call("asibot_services")
        self._send_mcp_request(payload, "tool_call: asibot_services")

    @task(15)
    @tag("tools", "github")
    def github_search_repos(self):
        """Search GitHub repositories."""
        query = random.choice(SEARCH_QUERIES)
        payload = _make_tool_call("github_search_repos", {"query": query, "limit": 10})
        self._send_mcp_request(payload, "tool_call: github_search_repos")

    @task(8)
    @tag("tools", "github")
    def github_search_code(self):
        """Search code across GitHub repos."""
        query = random.choice(SEARCH_QUERIES)
        payload = _make_tool_call("github_search_code", {"query": query, "limit": 5})
        self._send_mcp_request(payload, "tool_call: github_search_code")

    @task(8)
    @tag("tools", "github")
    def github_list_issues(self):
        """List issues for a random repo."""
        repo = random.choice(REPO_NAMES)
        state = random.choice(["open", "closed", "all"])
        payload = _make_tool_call("github_list_issues", {"repo": repo, "state": state, "limit": 15})
        self._send_mcp_request(payload, "tool_call: github_list_issues")

    @task(5)
    @tag("tools", "github")
    def github_list_repos(self):
        """List repos in the org."""
        payload = _make_tool_call("github_list_repos", {"limit": 20})
        self._send_mcp_request(payload, "tool_call: github_list_repos")

    @task(3)
    @tag("tools", "github")
    def github_list_commits(self):
        """List recent commits for a repo."""
        repo = random.choice(REPO_NAMES)
        payload = _make_tool_call("github_list_commits", {"repo": repo, "limit": 10})
        self._send_mcp_request(payload, "tool_call: github_list_commits")

    @task(3)
    @tag("tools", "github")
    def github_get_workflow_runs(self):
        """Get CI/CD workflow runs."""
        repo = random.choice(REPO_NAMES)
        payload = _make_tool_call("github_get_workflow_runs", {"repo": repo, "limit": 5})
        self._send_mcp_request(payload, "tool_call: github_get_workflow_runs")

    @task(2)
    @tag("tools", "jira")
    def jira_search(self):
        """Search Jira issues."""
        project = random.choice(JIRA_PROJECTS)
        query = f"project = {project} AND status = 'In Progress'"
        payload = _make_tool_call("jira_search", {"jql": query, "limit": 10})
        self._send_mcp_request(payload, "tool_call: jira_search")

    @task(2)
    @tag("tools", "confluence")
    def confluence_search(self):
        """Search Confluence pages."""
        query = random.choice(CONFLUENCE_QUERIES)
        payload = _make_tool_call("confluence_search", {"query": query, "limit": 5})
        self._send_mcp_request(payload, "tool_call: confluence_search")

    @task(2)
    @tag("tools", "connect")
    def connect_service(self):
        """Attempt to connect a service (exercises asibot_connect flow)."""
        service = random.choice(["github", "atlassian", "notion", "zendesk", "figma"])
        payload = _make_tool_call("asibot_connect", {"service": service})
        self._send_mcp_request(payload, "tool_call: asibot_connect")

    @task(1)
    @tag("setup")
    def setup_flow(self):
        """Trigger the account setup flow. Low weight since it is a one-time
        operation, but we test it under concurrency to verify rate limiting."""
        payload = _make_tool_call("asibot_setup")
        self._send_mcp_request(payload, "tool_call: asibot_setup")

    @task(1)
    @tag("setup")
    def setup_status(self):
        """Check setup status with a random setup_id (exercises the lookup path)."""
        fake_setup_id = uuid.uuid4().hex[:32]
        payload = _make_tool_call("asibot_setup_status", {"setup_id": fake_setup_id})
        self._send_mcp_request(payload, "tool_call: asibot_setup_status")

    @task(1)
    @tag("rate_limit")
    def burst_requests(self):
        """Send a burst of rapid requests to trigger rate limiting.

        This simulates a misbehaving client or automated tool that sends
        requests without think time, verifying the server enforces limits.
        """
        for i in range(15):
            payload = _make_tool_call("asibot_health")
            result = self._send_mcp_request(payload, "tool_call: burst_health")
            if result and isinstance(result, dict) and result.get("rate_limited"):
                # Successfully triggered rate limiting
                break

    @task(3)
    @tag("session")
    def session_reuse(self):
        """Make several requests in quick succession to verify session caching.

        The server should resolve the user from the cached session ID
        rather than hitting the database for every request.
        """
        # First request establishes the session
        payload1 = _make_tool_call("asibot_whoami")
        self._send_mcp_request(payload1, "tool_call: session_reuse_1")

        # Subsequent requests should hit session cache (lower latency)
        for i in range(3):
            payload = _make_tool_call("asibot_health")
            self._send_mcp_request(payload, "tool_call: session_reuse_cached")


# ---------------------------------------------------------------------------
# Unauthenticated user -- tests server behavior with no/bad auth
# ---------------------------------------------------------------------------


class UnauthenticatedUser(HttpUser):
    """Simulates users with no API key or invalid credentials.

    Verifies the server handles auth failures gracefully under load
    without leaking resources or crashing.
    """

    weight = 1  # 1 unauthenticated for every 10 authenticated (see McpUser weight)
    wait_time = between(2.0, 8.0)

    def _send_unauthenticated(self, payload: dict, name: str, headers: dict | None = None):
        """Send a request without valid auth."""
        default_headers = {
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        }
        if headers:
            default_headers.update(headers)

        with self.client.post(
            MCP_PATH,
            json=payload,
            headers=default_headers,
            name=name,
            catch_response=True,
        ) as response:
            # We expect 401/403 or a JSON-RPC error -- both are "correct"
            if response.status_code in (401, 403):
                response.success()
            elif response.status_code == 429:
                _custom_metrics["rate_limit_hits"].append(response.elapsed.total_seconds() * 1000)
                response.success()
            elif response.status_code < 400:
                # Some endpoints (health) may succeed without auth
                response.success()
            else:
                response.failure(f"Unexpected {response.status_code}")

    @task(5)
    @tag("auth", "no_key")
    def no_api_key(self):
        """Request with no Authorization header."""
        payload = _make_tool_call("asibot_whoami")
        self._send_unauthenticated(payload, "auth: no_key")

    @task(5)
    @tag("auth", "bad_key")
    def invalid_api_key(self):
        """Request with a malformed API key."""
        bad_key = "invalid_" + "".join(random.choices(string.ascii_letters, k=20))
        payload = _make_tool_call("asibot_whoami")
        self._send_unauthenticated(
            payload,
            "auth: invalid_key",
            headers={"Authorization": f"Bearer {bad_key}"},
        )

    @task(2)
    @tag("auth", "brute_force")
    def brute_force_auth(self):
        """Rapid auth attempts with random keys -- should trigger rate limiting."""
        for _ in range(12):
            bad_key = f"asb_{''.join(random.choices(string.ascii_letters, k=43))}"
            payload = _make_tool_call("asibot_whoami")
            self._send_unauthenticated(
                payload,
                "auth: brute_force_attempt",
                headers={"Authorization": f"Bearer {bad_key}"},
            )

    @task(3)
    @tag("auth", "health")
    def health_no_auth(self):
        """Health check without auth -- should succeed."""
        payload = _make_tool_call("asibot_health")
        self._send_unauthenticated(payload, "auth: health_no_auth")


# ---------------------------------------------------------------------------
# SSE response parser
# ---------------------------------------------------------------------------


def _parse_sse_response(body: str) -> dict | None:
    """Extract the last JSON-RPC result from an SSE event stream.

    MCP streamable-http returns events like:
        event: message
        data: {"jsonrpc": "2.0", "id": 1, "result": {...}}

    We parse and return the last data payload that contains a result.
    """
    last_result = None
    for line in body.split("\n"):
        line = line.strip()
        if line.startswith("data:"):
            data_str = line[5:].strip()
            if not data_str:
                continue
            try:
                parsed = json.loads(data_str)
                if isinstance(parsed, dict):
                    last_result = parsed
            except json.JSONDecodeError:
                continue
    return last_result


# ---------------------------------------------------------------------------
# Step load shape: ramp from 10 to 1000 users over 5 minutes
# ---------------------------------------------------------------------------


class StepLoadShape(LoadTestShape):
    """Ramp-up configuration:

    Phase 1 (0-1 min):   10 -> 100 users   (warm-up)
    Phase 2 (1-2 min):   100 -> 300 users   (moderate load)
    Phase 3 (2-3 min):   300 -> 600 users   (heavy load)
    Phase 4 (3-4 min):   600 -> 900 users   (near peak)
    Phase 5 (4-5 min):   900 -> 1000 users  (full load)
    Phase 6 (5-10 min):  1000 users          (sustained peak)
    Phase 7 (10-11 min): 1000 -> 0 users     (cool-down)
    """

    stages = [
        {"duration": 60, "users": 100, "spawn_rate": 2},      # warm-up
        {"duration": 120, "users": 300, "spawn_rate": 4},     # moderate
        {"duration": 180, "users": 600, "spawn_rate": 5},     # heavy
        {"duration": 240, "users": 900, "spawn_rate": 5},     # near peak
        {"duration": 300, "users": 1000, "spawn_rate": 2},    # full load
        {"duration": 600, "users": 1000, "spawn_rate": 1},    # sustained
        {"duration": 660, "users": 0, "spawn_rate": 20},      # cool-down
    ]

    def tick(self):
        run_time = self.get_run_time()

        for stage in self.stages:
            if run_time < stage["duration"]:
                return (stage["users"], stage["spawn_rate"])

        return None  # Stop the test


# ---------------------------------------------------------------------------
# McpUser weight -- 10x more authenticated users than unauthenticated
# ---------------------------------------------------------------------------

McpUser.weight = 10
